# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mira < Formula
  desc "A pretty, interactive folder visualizer for the terminal."
  homepage "https://github.com/mondial7/mira"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mondial7/mira/releases/download/v1.0.0/mira_1.0.0_darwin_x86_64.tar.gz"
      sha256 "6624627978e04861666b42c5d949e6fb0fafb08a74e6e3e90616d7ccb3b44d13"

      define_method(:install) do
        bin.install "mira"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mondial7/mira/releases/download/v1.0.0/mira_1.0.0_darwin_arm64.tar.gz"
      sha256 "1c909c104079817dc91b4230321adc7c9e9a8e0f86c66d3c457f1b1b76619b2a"

      define_method(:install) do
        bin.install "mira"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mondial7/mira/releases/download/v1.0.0/mira_1.0.0_linux_x86_64.tar.gz"
      sha256 "57ba07ccac04ca32354da316f4d90d48ce851b1b427d577be5cfeb3cc1ed1cbd"
      define_method(:install) do
        bin.install "mira"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mondial7/mira/releases/download/v1.0.0/mira_1.0.0_linux_arm64.tar.gz"
      sha256 "a6e45aaa6ee11d1b540128b49fbd0152a91717ab4d8cc0ed8cd8f6842ffeaec5"
      define_method(:install) do
        bin.install "mira"
      end
    end
  end

  test do
    system "#{bin}/mira", "--version"
  end
end
