# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mira < Formula
  desc "A pretty, interactive folder visualizer for the terminal."
  homepage "https://github.com/mondial7/mira"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mondial7/mira/releases/download/v1.1.0/mira_1.1.0_darwin_x86_64.tar.gz"
      sha256 "9b941558d29270da27f4b9e9d6a85a1df430e876c15b5c087d9c4d6f996b2c52"

      define_method(:install) do
        bin.install "mira"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mondial7/mira/releases/download/v1.1.0/mira_1.1.0_darwin_arm64.tar.gz"
      sha256 "c0f932052f8ac8a3ee661b180ca3c1fb7bcc65bb09461cfb880efc7070d9f83d"

      define_method(:install) do
        bin.install "mira"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mondial7/mira/releases/download/v1.1.0/mira_1.1.0_linux_x86_64.tar.gz"
      sha256 "964e3991754748ee4897e521bc49144346aefe4a9bd518432a0ea5dbf029d72a"
      define_method(:install) do
        bin.install "mira"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mondial7/mira/releases/download/v1.1.0/mira_1.1.0_linux_arm64.tar.gz"
      sha256 "1513200e2765fd8f740be621f4a9a327a21490499509bcfc0acd77a10d6badb3"
      define_method(:install) do
        bin.install "mira"
      end
    end
  end

  test do
    system "#{bin}/mira", "--version"
  end
end
