# This file was generated by GoReleaser. DO NOT EDIT.
cask "mondspace-reviewer" do
  version "5.1.1"

  on_macos do
    on_arm do
      sha256 "c4348076cd7a9e91f41573bca2e0cc23b4e6f020f886fdc4e15b5992ecd4aee6"
      url "https://github.com/mondial7/mondspace-reviewer/releases/download/v#{version}/mondspace-reviewer_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2be91b1d3369ac99bbc8624724fd0b13417a68f2878c6688db1db2884f6a73c6"
      url "https://github.com/mondial7/mondspace-reviewer/releases/download/v#{version}/mondspace-reviewer_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "62ac6c9d3e12a59adb4013f2a50a53109846940ebaac8c13f0192709b9bf7c73"
      url "https://github.com/mondial7/mondspace-reviewer/releases/download/v#{version}/mondspace-reviewer_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "15593af06139b2f6378075800080e2d2f5a86f880e3c0ec4633ec98275a6d647"
      url "https://github.com/mondial7/mondspace-reviewer/releases/download/v#{version}/mondspace-reviewer_#{version}_linux_amd64.tar.gz"
    end
  end

  name "mondspace-reviewer"
  desc "A review companion for autonomous coding agents."
  homepage "https://github.com/mondial7/mondspace-reviewer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mondspace-reviewer"

  postflight do
    # Gatekeeper blocks an unsigned binary that arrived with a quarantine
    # attribute, which is every cask download: macOS reports "Apple could
    # not verify … is free of malware" and offers only Move to Bin.
    #
    # Removing the attribute is the standard remedy for an unsigned
    # open-source CLI, and it is a real trade-off: it skips the
    # notarisation check for this file. The honest fix is a Developer ID
    # signature and notarisation, which needs an Apple developer account —
    # see the release notes.
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/mondspace-reviewer"]
    end
    # The docs call it msr, so brew users should not have to write an alias.
    FileUtils.ln_sf "#{HOMEBREW_PREFIX}/bin/mondspace-reviewer", "#{HOMEBREW_PREFIX}/bin/msr"
  end

  # No zap stanza required

  caveats <<~EOS
    Installed as both `mondspace-reviewer` and `msr`.
  EOS
end
