# This file was generated by GoReleaser. DO NOT EDIT.
cask "mondspace-reviewer" do
  version "6.0.0"

  on_macos do
    on_arm do
      sha256 "b4258b20a77e17e63a20767957aae040969bf9a4102407b04ee87210aa6979db"
      url "https://github.com/mondial7/mondspace-reviewer/releases/download/v#{version}/mondspace-reviewer_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "01ea9bc54e44b134ce5868e7bf2ed9f7b5925785f548d1b38e766bf1f86a1465"
      url "https://github.com/mondial7/mondspace-reviewer/releases/download/v#{version}/mondspace-reviewer_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7fbcd3023b591422e1eb475f22402f64dcf1bdf778487fee8e72e12961dc9b97"
      url "https://github.com/mondial7/mondspace-reviewer/releases/download/v#{version}/mondspace-reviewer_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "52e26d3a716c6bbd5b7371da9c18347c210dc3f53d2fcfcc1adedba59e7929c4"
      url "https://github.com/mondial7/mondspace-reviewer/releases/download/v#{version}/mondspace-reviewer_#{version}_linux_amd64.tar.gz"
    end
  end

  name "mondspace-reviewer"
  desc "A review companion for autonomous coding agents."
  homepage "https://github.com/mondial7/mondspace-reviewer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mondspace-reviewer"

  postflight do
    # Gatekeeper blocks an unsigned binary that arrived with a quarantine
    # attribute, which is every cask download: macOS reports "Apple could
    # not verify … is free of malware" and offers only Move to Bin.
    #
    # Removing the attribute is the standard remedy for an unsigned
    # open-source CLI, and it is a real trade-off: it skips the
    # notarisation check for this file. The honest fix is a Developer ID
    # signature and notarisation, which needs an Apple developer account —
    # see the release notes.
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/mondspace-reviewer"]
    end
    # The docs call it msr, so brew users should not have to write an alias.
    FileUtils.ln_sf "#{HOMEBREW_PREFIX}/bin/mondspace-reviewer", "#{HOMEBREW_PREFIX}/bin/msr"
  end

  # No zap stanza required

  caveats <<~EOS
    Installed as both `mondspace-reviewer` and `msr`.
  EOS
end
