# This file was generated by GoReleaser. DO NOT EDIT.
cask "mondspace-reviewer" do
  version "5.3.0"

  on_macos do
    on_arm do
      sha256 "4b6d63eeda4b932b797b8cea89dc781ec08edeaa3a50998a9f3b29074be4d9e5"
      url "https://github.com/mondial7/mondspace-reviewer/releases/download/v#{version}/mondspace-reviewer_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "95f10c7a1eff8fdecb5256c952242dc39472453d03c87b5db74fc710277f5c49"
      url "https://github.com/mondial7/mondspace-reviewer/releases/download/v#{version}/mondspace-reviewer_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "cc177864b7a10d9e1cd44227e250f9a0a6edf68b686bd3d898baf991218722ef"
      url "https://github.com/mondial7/mondspace-reviewer/releases/download/v#{version}/mondspace-reviewer_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "923fd51363cf39e00bc13253e6439b2e626564026b2a27ac1ced6ffa44e2d259"
      url "https://github.com/mondial7/mondspace-reviewer/releases/download/v#{version}/mondspace-reviewer_#{version}_linux_amd64.tar.gz"
    end
  end

  name "mondspace-reviewer"
  desc "A review companion for autonomous coding agents."
  homepage "https://github.com/mondial7/mondspace-reviewer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mondspace-reviewer"

  postflight do
    # Gatekeeper blocks an unsigned binary that arrived with a quarantine
    # attribute, which is every cask download: macOS reports "Apple could
    # not verify … is free of malware" and offers only Move to Bin.
    #
    # Removing the attribute is the standard remedy for an unsigned
    # open-source CLI, and it is a real trade-off: it skips the
    # notarisation check for this file. The honest fix is a Developer ID
    # signature and notarisation, which needs an Apple developer account —
    # see the release notes.
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/mondspace-reviewer"]
    end
    # The docs call it msr, so brew users should not have to write an alias.
    FileUtils.ln_sf "#{HOMEBREW_PREFIX}/bin/mondspace-reviewer", "#{HOMEBREW_PREFIX}/bin/msr"
  end

  # No zap stanza required

  caveats <<~EOS
    Installed as both `mondspace-reviewer` and `msr`.
  EOS
end
